//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StylingAButton {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StylingAButton.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string ComputerFont {
            get {
                return ResourceManager.GetString("ComputerFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A computer font (or font) is a digital data file, containing a set of graphically related glyphs, characters, or symbols. Although the term font first referred to a set of movable metal type pieces in one style and size, since around 1990s it is generally used to refer to a set of digital shapes in a single style, scalable to different sizes.
        ///A definition from Microsoft describe font as &quot;A graphic design applied to a collection of numbers, symbols, and characters that describes a certain typeface, along wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ComputerFontContent {
            get {
                return ResourceManager.GetString("ComputerFontContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string ComputingButton {
            get {
                return ResourceManager.GetString("ComputingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term button in computing, also known as command button, refers to a graphical control element that provides the user with a simple way of interacting with system. Microsoft gives the following definition of a button: &quot;A graphic element that appears similar to physical button or keyboard key in the user interface. A button is &quot;pressed&quot; by clicking on it with a mouse, by hitting Enter or Space on the keyboard, if the button has the focus, or by tapping by a finger (if the display supports it).&quot;
        ///
        ///A typic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ComputingButtonContent {
            get {
                return ResourceManager.GetString("ComputingButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system.
        /// </summary>
        public static string WritingSystem {
            get {
                return ResourceManager.GetString("WritingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A writing system (or script) is a method of visually representing verbal communication. While both writing and speech are useful in conveying messages, writting differs in also being a reliable form of information storage and transfer. 
        ///
        ///Several approaches have been taken to classify writting systems, the most common and basic one is a broad division into three categories: logographic, syllabic and alphabetic. However, all three may be found in any given writing system in varying proportions, often making [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WritingSystemContent {
            get {
                return ResourceManager.GetString("WritingSystemContent", resourceCulture);
            }
        }
    }
}
